import type { CacheEntry, SimulationRequest } from './types'

/** Time-to-live for cached simulation results (30 minutes). */
export const SIMULATION_TTL_MS = 1000 * 60 * 30

/**
 * In-memory cache store. Keys are generated by `generateCacheKey`.
 * Values are generic `CacheEntry<T>` wrappers that carry TTL metadata.
 */
const cache = new Map<string, CacheEntry<unknown>>()

/**
 * Derives a stable, compact cache key from a `SimulationRequest`.
 *
 * Steps:
 * 1. Concatenate context, constraint, stakeholders, and urgency.
 * 2. Lowercase and collapse all whitespace to a single space.
 * 3. Trim to the first 300 characters to bound key length.
 * 4. Compute a simple numeric hash (sum of char codes) and encode in base-36.
 *
 * @param scenario - The simulation request whose fields form the key.
 * @returns A short base-36 hash string.
 */
export function generateCacheKey(scenario: SimulationRequest): string {
  const raw = `${scenario.context} ${scenario.constraint} ${scenario.stakeholders} ${scenario.urgency}`
  const normalised = raw.toLowerCase().replace(/\s+/g, ' ').trim().slice(0, 300)

  let hash = 0
  for (let i = 0; i < normalised.length; i++) {
    hash += normalised.charCodeAt(i)
  }

  return hash.toString(36)
}

/**
 * Retrieves a cached value by key, respecting its TTL.
 *
 * @param key - The cache key produced by `generateCacheKey`.
 * @returns The stored data of type `T`, or `null` if the entry is missing or expired.
 */
export function getCached<T>(key: string): T | null {
  const entry = cache.get(key) as CacheEntry<T> | undefined

  if (!entry) return null

  const isExpired = Date.now() - entry.created_at > entry.ttl
  if (isExpired) {
    cache.delete(key)
    return null
  }

  return entry.data
}

/**
 * Stores a value in the cache under the given key with a specified TTL.
 *
 * @param key   - The cache key produced by `generateCacheKey`.
 * @param data  - The value to cache.
 * @param ttlMs - How long (in milliseconds) the entry remains valid.
 */
export function setCached<T>(key: string, data: T, ttlMs: number): void {
  const entry: CacheEntry<T> = {
    data,
    created_at: Date.now(),
    ttl: ttlMs,
  }
  cache.set(key, entry as CacheEntry<unknown>)
}
