/**
 * Represents the raw input provided by the user when setting up a decision scenario.
 * Used to collect context, constraints, stakeholders, and urgency before running a simulation.
 */
export interface DecisionScenario {
  context: string
  constraint: string
  stakeholders: string
  urgency: 'low' | 'medium' | 'high' | 'critical'
}

/**
 * Describes a single strategic option generated by the AI for a given decision scenario.
 * Contains structured pros, cons, risks, timeline, and a confidence score for comparison.
 */
export interface StrategicOption {
  id: string
  title: string
  approach: string
  pros: string[]
  cons: string[]
  risks: string[]
  estimated_timeline: string
  confidence_score: number
  recommended: boolean
}

/**
 * The full result returned by the AI simulation engine for a decision scenario.
 * Includes all generated strategic options, the recommended choice, and evaluation metadata.
 */
export interface SimulationResult {
  scenario_summary: string
  options: StrategicOption[]
  recommended_option_id: string
  recommendation_rationale: string
  key_tradeoff: string
  evaluated_at: string
  cached: boolean
}

/**
 * The payload sent by the client to the simulation API endpoint.
 * Mirrors DecisionScenario but kept separate to allow independent API versioning.
 */
export interface SimulationRequest {
  context: string
  constraint: string
  stakeholders: string
  urgency: 'low' | 'medium' | 'high' | 'critical'
}

/**
 * A generic TTL-aware cache wrapper used to store any value with an expiry policy.
 * Used by the server-side cache layer to avoid redundant AI API calls.
 */
export interface CacheEntry<T> {
  data: T
  created_at: number
  ttl: number
}
